# SPDX-License-Identifier: GPL-3.0-or-later
# Included by each GLKVM TLS server through extras/*/nginx.ctx-server.conf.
location = /command {
    return 302 /command/;
}
location /command/ {
    alias /usr/share/kvmcontrol/web/command/;
    index index.html;
    auth_request /auth_check;
    include /etc/kvmd/nginx/loc-login.conf;
    include /etc/kvmd/nginx/loc-nocache.conf;
}
location /command/static/ {
    alias /usr/share/kvmcontrol/web/static/;
    auth_request off;
    include /etc/kvmd/nginx/loc-nocache.conf;
}
location = /api/scheduler {
    auth_request /auth_check;
    rewrite ^/api/(.*)$ /$1 break;
    proxy_pass http://unix:/run/kvmcontrol/automation.sock;
    include /etc/kvmd/nginx/loc-proxy.conf;
    client_max_body_size 8k;
    proxy_read_timeout 35s;
}
location /api/scheduler/ {
    auth_request /auth_check;
    rewrite ^/api/(.*)$ /$1 break;
    proxy_pass http://unix:/run/kvmcontrol/automation.sock;
    include /etc/kvmd/nginx/loc-proxy.conf;
    client_max_body_size 8k;
    proxy_read_timeout 35s;
}
